import Header from "@/components/ui/Header/Header";
import Navbar from "@/components/ui/Navbar/Navbar";
import ThemeRegistry from "@/theme/EmotionCache";
import { AppBar, Box } from "@mui/material";
import type { Metadata } from "next";
import "./globals.css";
import { StoreProviders } from "@/redux/StoreProviders";
import RigtDrawer from "@/components/ui/Drawer/Drawer";
import SnackBar from "@/components/ui/SnackBar/SnackBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProviders>
          <ThemeRegistry>
            <AppBar
              position="fixed"
              sx={{ backgroundColor: "cBackground.dark", boxShadow: "none" }}
            >
              <Header />
              <Navbar />
            </AppBar>
            <RigtDrawer />
            <Box
              component="main"
              sx={{
                bgcolor: "cBackground.dark",
                mt: { xs: "64px", md: "140px" },
              }}
            >
              {children}
            </Box>
          </ThemeRegistry>
          <SnackBar />
        </StoreProviders>
      </body>
    </html>
  );
}
